export const siteConfig = {
  name: 'Dr. Nitya Nutan Misra',
  title: 'Best Doctor in Cuttack | Dr. Nitya Nutan Misra | Book Appointment',
  description:
    'Looking for the best doctor in Cuttack & Bhubaneswar? Dr. Nitya Nutan Misra is a top Surgical Oncologist & Cancer Specialist in Odisha. Book an appointment today for expert care in Breast, Head & Neck, GI, and Thyroid Cancer.',
  url: 'https://drnityanutanmisra.com',
  phone: '+919438844662',
  phoneDisplay: '+91 94388 44662',
  whatsapp: '919438844662',
  email: 'contact@drnityanutanmisra.com',
  address: 'Sai shree polyclinic, At- Kathagola, Ring Rd, near Shree Maa Hospital, Cuttack, Odisha 753001',
  hospital: 'Sai shree polyclinic',
  city: 'Cuttack, Odisha 753001',
  specialization: 'Surgical Oncologist',
  designation: 'Assistant Professor',
  tagline: 'Early diagnosis saves lives.',
  keywords: [
    'best doctor in cuttack',
    'best doctor in bhubaneswar',
    'clinic in odisha',
    'surgical oncologist odisha',
    'cancer surgeon cuttack',
    'breast cancer surgery odisha',
    'head neck cancer surgeon',
    'gastrointestinal cancer specialist',
    'thyroid tumor surgery',
    'sarcoma specialist',
    'AHPGIC doctor',
    'cancer hospital cuttack',
    'oncology surgeon india',
    'top cancer doctor near me',
  ],
  social: {
    twitter: 'https://twitter.com/',
    linkedin: 'https://linkedin.com/',
  },
  og: {
    image: '/images/og-image.jpg',
  },
}
